# Generated by Django 3.2.18 on 2023-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
