# Generated by Django 4.2.1 on 2023-11-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
        ('client', '0004_alter_appoint_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAppoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alloted_time', models.DateTimeField(blank=True, null=True)),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doc.doctor')),
            ],
        ),
    ]
