# Generated by Django 4.2.1 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=200)),
                ('i_result', models.CharField(max_length=200)),
                ('i_price', models.IntegerField()),
            ],
        ),
    ]
