# Generated by Django 3.2.18 on 2023-11-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/doc')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('spec', models.CharField(max_length=120)),
                ('edu', models.CharField(max_length=40)),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
