# Generated by Django 4.2.1 on 2023-11-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_docappoint'),
        ('med', '0002_investigation'),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docsuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Presc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('docsuggest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.docsuggest')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.doctor')),
                ('med', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.medicen')),
            ],
        ),
        migrations.CreateModel(
            name='Inves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docsuggest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.docsuggest')),
                ('inves', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.investigation')),
            ],
        ),
        migrations.AddField(
            model_name='docsuggest',
            name='investigations',
            field=models.ManyToManyField(blank=True, related_name='investigations', to='doc.inves'),
        ),
        migrations.AddField(
            model_name='docsuggest',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='doc.presc'),
        ),
    ]
